vim.api.nvim_set_keymap('n', '<TAB>', ':BufferNext<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<S-TAB>', ':BufferPrevious<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<S-x>', ':BufferClose<CR>', { noremap = true, silent = true })
vim.api.fg_target('red')
vim.api.fg_current(s:fg(['Normal'], '#efefef'))
vim.api.fg_visible(s:fg(['TabLineSel'], '#efefef'))
vim.api.fg_inactive(s:fg(['TabLineFill'], '#888888'))
vim.api.fg_modified(s:fg(['WarningMsg'], '#E5AB0E'))
vim.api.fg_special(s:fg(['Special'], '#599eff'))
vim.api.fg_subtle(s:fg(['NonText', 'Comment'], '#555555'))
vim.api.bg_current(s:bg(['Normal'], '#000000'))
vim.api.bg_visible(s:bg(['TabLineSel', 'Normal'], '#000000'))
vim.api.bg_inactive(s:bg(['TabLineFill', 'StatusLine'], '#000000'))
